version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  certinfo:
    lang: golang-http
    handler: ./certinfo
    image: certinfo:latest
    build_args:
      GO111MODULE: on
